export const galleryItems = [
  {
    "id": "gal-1",
    "title": "HackSeries 25th Flagship Keynote #1",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-1.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-1.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-1.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-1.webp"
  },
  {
    "id": "gal-2",
    "title": "HackSeries 25th Flagship Keynote #2",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-2.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-2.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-2.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-2.webp"
  },
  {
    "id": "gal-3",
    "title": "HackSeries 25th Flagship Keynote #3",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-3.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-3.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-3.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-3.webp"
  },
  {
    "id": "gal-4",
    "title": "HackSeries 25th Flagship Keynote #4",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-4.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-4.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-4.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-4.webp"
  },
  {
    "id": "gal-5",
    "title": "HackSeries 25th Flagship Keynote #5",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-5.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-5.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-5.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-5.webp"
  },
  {
    "id": "gal-6",
    "title": "HackSeries 25th Flagship Keynote #6",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-6.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-6.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-6.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-6.webp"
  },
  {
    "id": "gal-7",
    "title": "HackSeries 25th Flagship Keynote #7",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-25-7.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-7.jpg",
    "caption": "Opening address, team registrations, and briefing on problem statements during HackSeries 25.",
    "year": "2025",
    "location": "DIT Main Auditorium",
    "imageWebp": "/images/gallery/hackseries-25-7.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-7.webp"
  },
  {
    "id": "gal-8",
    "title": "HackSeries 25th Coding Sprints #1",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-8.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-8.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-8.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-8.webp"
  },
  {
    "id": "gal-9",
    "title": "HackSeries 25th Coding Sprints #2",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-9.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-9.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-9.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-9.webp"
  },
  {
    "id": "gal-10",
    "title": "HackSeries 25th Coding Sprints #3",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-10.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-10.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-10.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-10.webp"
  },
  {
    "id": "gal-11",
    "title": "HackSeries 25th Coding Sprints #4",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-11.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-11.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-11.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-11.webp"
  },
  {
    "id": "gal-12",
    "title": "HackSeries 25th Coding Sprints #5",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-12.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-12.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-12.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-12.webp"
  },
  {
    "id": "gal-13",
    "title": "HackSeries 25th Coding Sprints #6",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-13.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-13.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-13.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-13.webp"
  },
  {
    "id": "gal-14",
    "title": "HackSeries 25th Coding Sprints #7",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-14.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-14.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-14.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-14.webp"
  },
  {
    "id": "gal-15",
    "title": "HackSeries 25th Coding Sprints #8",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-15.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-15.jpg",
    "caption": "Engineering squads collaborating intensively on architecture design and prototyping.",
    "year": "2025",
    "location": "ACES Computing Lab",
    "imageWebp": "/images/gallery/hackseries-25-15.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-15.webp"
  },
  {
    "id": "gal-16",
    "title": "Mentor Review & Code Diagnostics #1",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-16.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-16.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-16.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-16.webp"
  },
  {
    "id": "gal-17",
    "title": "Mentor Review & Code Diagnostics #2",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-17.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-17.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-17.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-17.webp"
  },
  {
    "id": "gal-18",
    "title": "Mentor Review & Code Diagnostics #3",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-18.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-18.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-18.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-18.webp"
  },
  {
    "id": "gal-19",
    "title": "Mentor Review & Code Diagnostics #4",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-19.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-19.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-19.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-19.webp"
  },
  {
    "id": "gal-20",
    "title": "Mentor Review & Code Diagnostics #5",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-20.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-20.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-20.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-20.webp"
  },
  {
    "id": "gal-21",
    "title": "Mentor Review & Code Diagnostics #6",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-21.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-21.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-21.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-21.webp"
  },
  {
    "id": "gal-22",
    "title": "Mentor Review & Code Diagnostics #7",
    "category": "Workshops",
    "image": "/images/gallery/hackseries-25-22.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-22.jpg",
    "caption": "Domain specialists and technical mentors reviewing team git repositories and system design.",
    "year": "2025",
    "location": "Innovation Floor",
    "imageWebp": "/images/gallery/hackseries-25-22.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-22.webp"
  },
  {
    "id": "gal-23",
    "title": "Student Collaboration Hub #1",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-23.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-23.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-23.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-23.webp"
  },
  {
    "id": "gal-24",
    "title": "Student Collaboration Hub #2",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-24.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-24.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-24.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-24.webp"
  },
  {
    "id": "gal-25",
    "title": "Student Collaboration Hub #3",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-25.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-25.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-25.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-25.webp"
  },
  {
    "id": "gal-26",
    "title": "Student Collaboration Hub #4",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-26.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-26.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-26.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-26.webp"
  },
  {
    "id": "gal-27",
    "title": "Student Collaboration Hub #5",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-27.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-27.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-27.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-27.webp"
  },
  {
    "id": "gal-28",
    "title": "Student Collaboration Hub #6",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-28.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-28.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-28.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-28.webp"
  },
  {
    "id": "gal-29",
    "title": "Student Collaboration Hub #7",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-29.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-29.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-29.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-29.webp"
  },
  {
    "id": "gal-30",
    "title": "Student Collaboration Hub #8",
    "category": "Technical",
    "image": "/images/gallery/hackseries-25-30.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-30.jpg",
    "caption": "Engaged developers and UI/UX designers building responsive full-stack solutions.",
    "year": "2025",
    "location": "Central Tech Arena",
    "imageWebp": "/images/gallery/hackseries-25-30.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-30.webp"
  },
  {
    "id": "gal-31",
    "title": "HackSeries 25th Showcase & Felicitation #1",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-31.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-31.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-31.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-31.webp"
  },
  {
    "id": "gal-32",
    "title": "HackSeries 25th Showcase & Felicitation #2",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-32.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-32.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-32.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-32.webp"
  },
  {
    "id": "gal-33",
    "title": "HackSeries 25th Showcase & Felicitation #3",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-33.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-33.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-33.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-33.webp"
  },
  {
    "id": "gal-34",
    "title": "HackSeries 25th Showcase & Felicitation #4",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-34.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-34.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-34.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-34.webp"
  },
  {
    "id": "gal-35",
    "title": "HackSeries 25th Showcase & Felicitation #5",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-35.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-35.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-35.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-35.webp"
  },
  {
    "id": "gal-36",
    "title": "HackSeries 25th Showcase & Felicitation #6",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-36.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-36.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-36.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-36.webp"
  },
  {
    "id": "gal-37",
    "title": "HackSeries 25th Showcase & Felicitation #7",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-37.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-37.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-37.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-37.webp"
  },
  {
    "id": "gal-38",
    "title": "HackSeries 25th Showcase & Felicitation #8",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-38.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-38.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-38.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-38.webp"
  },
  {
    "id": "gal-39",
    "title": "HackSeries 25th Showcase & Felicitation #9",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-39.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-39.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-39.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-39.webp"
  },
  {
    "id": "gal-40",
    "title": "HackSeries 25th Showcase & Felicitation #10",
    "category": "Leadership",
    "image": "/images/gallery/hackseries-25-40.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-25-40.jpg",
    "caption": "Ceremony honoring outstanding project submissions, open-source work, and committee leadership.",
    "year": "2025",
    "location": "DIT Seminar Hall",
    "imageWebp": "/images/gallery/hackseries-25-40.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-25-40.webp"
  },
  {
    "id": "gal-41",
    "title": "National Hackathon Pitch Stage #1",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-1.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-1.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-1.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-1.webp"
  },
  {
    "id": "gal-42",
    "title": "National Hackathon Pitch Stage #2",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-2.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-2.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-2.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-2.webp"
  },
  {
    "id": "gal-43",
    "title": "National Hackathon Pitch Stage #3",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-3.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-3.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-3.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-3.webp"
  },
  {
    "id": "gal-44",
    "title": "National Hackathon Pitch Stage #4",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-4.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-4.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-4.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-4.webp"
  },
  {
    "id": "gal-45",
    "title": "National Hackathon Pitch Stage #5",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-5.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-5.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-5.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-5.webp"
  },
  {
    "id": "gal-46",
    "title": "National Hackathon Pitch Stage #6",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-6.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-6.jpg",
    "caption": "Finalist squads demonstrating working AI and web prototypes live to the jury panel.",
    "year": "2026",
    "location": "Main Stage, Pune",
    "imageWebp": "/images/gallery/hackathon-main-6.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-6.webp"
  },
  {
    "id": "gal-47",
    "title": "24-Hour Hackathon Development #1",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-7.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-7.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-7.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-7.webp"
  },
  {
    "id": "gal-48",
    "title": "24-Hour Hackathon Development #2",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-8.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-8.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-8.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-8.webp"
  },
  {
    "id": "gal-49",
    "title": "24-Hour Hackathon Development #3",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-9.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-9.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-9.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-9.webp"
  },
  {
    "id": "gal-50",
    "title": "24-Hour Hackathon Development #4",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-10.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-10.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-10.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-10.webp"
  },
  {
    "id": "gal-51",
    "title": "24-Hour Hackathon Development #5",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-11.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-11.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-11.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-11.webp"
  },
  {
    "id": "gal-52",
    "title": "24-Hour Hackathon Development #6",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-12.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-12.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-12.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-12.webp"
  },
  {
    "id": "gal-53",
    "title": "24-Hour Hackathon Development #7",
    "category": "Technical",
    "image": "/images/gallery/hackathon-main-13.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-13.jpg",
    "caption": "Teams pushing commits late into the night during the national hackathon sprint.",
    "year": "2026",
    "location": "Tech Hub Lab 4",
    "imageWebp": "/images/gallery/hackathon-main-13.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-13.webp"
  },
  {
    "id": "gal-54",
    "title": "Jury Evaluation & Architecture Review #1",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-14.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-14.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-14.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-14.webp"
  },
  {
    "id": "gal-55",
    "title": "Jury Evaluation & Architecture Review #2",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-15.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-15.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-15.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-15.webp"
  },
  {
    "id": "gal-56",
    "title": "Jury Evaluation & Architecture Review #3",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-16.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-16.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-16.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-16.webp"
  },
  {
    "id": "gal-57",
    "title": "Jury Evaluation & Architecture Review #4",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-17.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-17.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-17.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-17.webp"
  },
  {
    "id": "gal-58",
    "title": "Jury Evaluation & Architecture Review #5",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-18.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-18.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-18.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-18.webp"
  },
  {
    "id": "gal-59",
    "title": "Jury Evaluation & Architecture Review #6",
    "category": "Workshops",
    "image": "/images/gallery/hackathon-main-19.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-19.jpg",
    "caption": "Judges and faculty reviewing live deployments, API endpoints, and database models.",
    "year": "2026",
    "location": "Exhibition Hall",
    "imageWebp": "/images/gallery/hackathon-main-19.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-19.webp"
  },
  {
    "id": "gal-60",
    "title": "Hackathon Grand Finale & Awards #1",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-20.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-20.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-20.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-20.webp"
  },
  {
    "id": "gal-61",
    "title": "Hackathon Grand Finale & Awards #2",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-21.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-21.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-21.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-21.webp"
  },
  {
    "id": "gal-62",
    "title": "Hackathon Grand Finale & Awards #3",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-22.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-22.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-22.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-22.webp"
  },
  {
    "id": "gal-63",
    "title": "Hackathon Grand Finale & Awards #4",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-23.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-23.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-23.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-23.webp"
  },
  {
    "id": "gal-64",
    "title": "Hackathon Grand Finale & Awards #5",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-24.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-24.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-24.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-24.webp"
  },
  {
    "id": "gal-65",
    "title": "Hackathon Grand Finale & Awards #6",
    "category": "Hackathons",
    "image": "/images/gallery/hackathon-main-25.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-main-25.jpg",
    "caption": "Winners felicitated on stage with trophies, certificates, and cash prizes.",
    "year": "2026",
    "location": "Grand Auditorium",
    "imageWebp": "/images/gallery/hackathon-main-25.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-main-25.webp"
  },
  {
    "id": "gal-66",
    "title": "ACES Organizing Crew & Operations #1",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-1.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-1.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-1.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-1.webp"
  },
  {
    "id": "gal-67",
    "title": "ACES Organizing Crew & Operations #2",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-2.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-2.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-2.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-2.webp"
  },
  {
    "id": "gal-68",
    "title": "ACES Organizing Crew & Operations #3",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-3.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-3.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-3.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-3.webp"
  },
  {
    "id": "gal-69",
    "title": "ACES Organizing Crew & Operations #4",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-4.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-4.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-4.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-4.webp"
  },
  {
    "id": "gal-70",
    "title": "ACES Organizing Crew & Operations #5",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-5.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-5.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-5.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-5.webp"
  },
  {
    "id": "gal-71",
    "title": "ACES Organizing Crew & Operations #6",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-6.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-6.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-6.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-6.webp"
  },
  {
    "id": "gal-72",
    "title": "ACES Organizing Crew & Operations #7",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-7.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-7.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-7.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-7.webp"
  },
  {
    "id": "gal-73",
    "title": "ACES Organizing Crew & Operations #8",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-8.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-8.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-8.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-8.webp"
  },
  {
    "id": "gal-74",
    "title": "ACES Organizing Crew & Operations #9",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-9.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-9.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-9.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-9.webp"
  },
  {
    "id": "gal-75",
    "title": "ACES Organizing Crew & Operations #10",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-10.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-10.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-10.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-10.webp"
  },
  {
    "id": "gal-76",
    "title": "ACES Organizing Crew & Operations #11",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-11.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-11.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-11.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-11.webp"
  },
  {
    "id": "gal-77",
    "title": "ACES Organizing Crew & Operations #12",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-12.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-12.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-12.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-12.webp"
  },
  {
    "id": "gal-78",
    "title": "ACES Organizing Crew & Operations #13",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-13.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-13.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-13.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-13.webp"
  },
  {
    "id": "gal-79",
    "title": "ACES Organizing Crew & Operations #14",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-14.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-14.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-14.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-14.webp"
  },
  {
    "id": "gal-80",
    "title": "ACES Organizing Crew & Operations #15",
    "category": "Leadership",
    "image": "/images/gallery/hackathon-bts-15.jpg",
    "thumb": "/images/gallery/thumbs/hackathon-bts-15.jpg",
    "caption": "Behind-the-scenes event logistics, stage management, live streaming, and volunteer coordination.",
    "year": "2026",
    "location": "Backstage & Control Room",
    "imageWebp": "/images/gallery/hackathon-bts-15.webp",
    "thumbWebp": "/images/gallery/thumbs/hackathon-bts-15.webp"
  },
  {
    "id": "gal-81",
    "title": "Indo-German Tech & Academic Exchange #1",
    "category": "Workshops",
    "image": "/images/gallery/german-event-1.jpg",
    "thumb": "/images/gallery/thumbs/german-event-1.jpg",
    "caption": "Guest delegation and visiting professors sharing global tech perspectives and research opportunities.",
    "year": "2025",
    "location": "International Conference Hall",
    "imageWebp": "/images/gallery/german-event-1.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-1.webp"
  },
  {
    "id": "gal-82",
    "title": "Indo-German Tech & Academic Exchange #2",
    "category": "Workshops",
    "image": "/images/gallery/german-event-2.jpg",
    "thumb": "/images/gallery/thumbs/german-event-2.jpg",
    "caption": "Guest delegation and visiting professors sharing global tech perspectives and research opportunities.",
    "year": "2025",
    "location": "International Conference Hall",
    "imageWebp": "/images/gallery/german-event-2.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-2.webp"
  },
  {
    "id": "gal-83",
    "title": "Indo-German Tech & Academic Exchange #3",
    "category": "Workshops",
    "image": "/images/gallery/german-event-3.jpg",
    "thumb": "/images/gallery/thumbs/german-event-3.jpg",
    "caption": "Guest delegation and visiting professors sharing global tech perspectives and research opportunities.",
    "year": "2025",
    "location": "International Conference Hall",
    "imageWebp": "/images/gallery/german-event-3.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-3.webp"
  },
  {
    "id": "gal-84",
    "title": "Indo-German Tech & Academic Exchange #4",
    "category": "Workshops",
    "image": "/images/gallery/german-event-4.jpg",
    "thumb": "/images/gallery/thumbs/german-event-4.jpg",
    "caption": "Guest delegation and visiting professors sharing global tech perspectives and research opportunities.",
    "year": "2025",
    "location": "International Conference Hall",
    "imageWebp": "/images/gallery/german-event-4.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-4.webp"
  },
  {
    "id": "gal-85",
    "title": "Global Education & Engineering Seminar #1",
    "category": "Leadership",
    "image": "/images/gallery/german-event-5.jpg",
    "thumb": "/images/gallery/thumbs/german-event-5.jpg",
    "caption": "Interactive Q&A on higher education, robotics research, and overseas engineering careers.",
    "year": "2025",
    "location": "Seminar Hall 2",
    "imageWebp": "/images/gallery/german-event-5.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-5.webp"
  },
  {
    "id": "gal-86",
    "title": "Global Education & Engineering Seminar #2",
    "category": "Leadership",
    "image": "/images/gallery/german-event-6.jpg",
    "thumb": "/images/gallery/thumbs/german-event-6.jpg",
    "caption": "Interactive Q&A on higher education, robotics research, and overseas engineering careers.",
    "year": "2025",
    "location": "Seminar Hall 2",
    "imageWebp": "/images/gallery/german-event-6.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-6.webp"
  },
  {
    "id": "gal-87",
    "title": "Global Education & Engineering Seminar #3",
    "category": "Leadership",
    "image": "/images/gallery/german-event-7.jpg",
    "thumb": "/images/gallery/thumbs/german-event-7.jpg",
    "caption": "Interactive Q&A on higher education, robotics research, and overseas engineering careers.",
    "year": "2025",
    "location": "Seminar Hall 2",
    "imageWebp": "/images/gallery/german-event-7.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-7.webp"
  },
  {
    "id": "gal-88",
    "title": "Cross-Cultural Student Interaction #1",
    "category": "Cultural",
    "image": "/images/gallery/german-event-8.jpg",
    "thumb": "/images/gallery/thumbs/german-event-8.jpg",
    "caption": "Students interacting with international guests, exchanging ideas, and celebrating academic synergy.",
    "year": "2025",
    "location": "ACES Tech Lounge",
    "imageWebp": "/images/gallery/german-event-8.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-8.webp"
  },
  {
    "id": "gal-89",
    "title": "Cross-Cultural Student Interaction #2",
    "category": "Cultural",
    "image": "/images/gallery/german-event-9.jpg",
    "thumb": "/images/gallery/thumbs/german-event-9.jpg",
    "caption": "Students interacting with international guests, exchanging ideas, and celebrating academic synergy.",
    "year": "2025",
    "location": "ACES Tech Lounge",
    "imageWebp": "/images/gallery/german-event-9.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-9.webp"
  },
  {
    "id": "gal-90",
    "title": "Cross-Cultural Student Interaction #3",
    "category": "Cultural",
    "image": "/images/gallery/german-event-10.jpg",
    "thumb": "/images/gallery/thumbs/german-event-10.jpg",
    "caption": "Students interacting with international guests, exchanging ideas, and celebrating academic synergy.",
    "year": "2025",
    "location": "ACES Tech Lounge",
    "imageWebp": "/images/gallery/german-event-10.webp",
    "thumbWebp": "/images/gallery/thumbs/german-event-10.webp"
  },
  {
    "id": "gal-91",
    "title": "HackSeries 0.1 Inception & Kickoff #91",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-1.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-1.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-1.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-1.webp"
  },
  {
    "id": "gal-92",
    "title": "HackSeries 0.1 Inception & Kickoff #92",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-2.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-2.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-2.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-2.webp"
  },
  {
    "id": "gal-93",
    "title": "HackSeries 0.1 Inception & Kickoff #93",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-3.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-3.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-3.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-3.webp"
  },
  {
    "id": "gal-94",
    "title": "HackSeries 0.1 Inception & Kickoff #94",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-4.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-4.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-4.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-4.webp"
  },
  {
    "id": "gal-95",
    "title": "HackSeries 0.1 Inception & Kickoff #95",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-5.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-5.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-5.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-5.webp"
  },
  {
    "id": "gal-96",
    "title": "HackSeries 0.1 Inception & Kickoff #96",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-01-6.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-01-6.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-01-6.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-01-6.webp"
  },
  {
    "id": "gal-97",
    "title": "HackSeries 0.1 Inception & Kickoff #97",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-alt-1.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-alt-1.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-alt-1.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-alt-1.webp"
  },
  {
    "id": "gal-98",
    "title": "HackSeries 0.1 Inception & Kickoff #98",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-alt-2.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-alt-2.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-alt-2.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-alt-2.webp"
  },
  {
    "id": "gal-99",
    "title": "HackSeries 0.1 Inception & Kickoff #99",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-alt-3.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-alt-3.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-alt-3.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-alt-3.webp"
  },
  {
    "id": "gal-100",
    "title": "HackSeries 0.1 Inception & Kickoff #100",
    "category": "Hackathons",
    "image": "/images/gallery/hackseries-alt-4.jpg",
    "thumb": "/images/gallery/thumbs/hackseries-alt-4.jpg",
    "caption": "Inaugural edition of the HackSeries franchise bringing early-year developers together.",
    "year": "2025",
    "location": "ACES Innovation Lab",
    "imageWebp": "/images/gallery/hackseries-alt-4.webp",
    "thumbWebp": "/images/gallery/thumbs/hackseries-alt-4.webp"
  }
];

export const marqueeImages = [
  {
    "id": "mq-1",
    "url": "/images/gallery/thumbs/hackseries-25-1.jpg",
    "alt": "HackSeries 25th Flagship Keynote #1",
    "urlWebp": "/images/gallery/thumbs/hackseries-25-1.webp"
  },
  {
    "id": "mq-2",
    "url": "/images/gallery/thumbs/hackseries-25-8.jpg",
    "alt": "HackSeries 25th Coding Sprints #1",
    "urlWebp": "/images/gallery/thumbs/hackseries-25-8.webp"
  },
  {
    "id": "mq-3",
    "url": "/images/gallery/thumbs/hackseries-25-16.jpg",
    "alt": "Mentor Review & Code Diagnostics #1",
    "urlWebp": "/images/gallery/thumbs/hackseries-25-16.webp"
  },
  {
    "id": "mq-4",
    "url": "/images/gallery/thumbs/hackseries-25-23.jpg",
    "alt": "Student Collaboration Hub #1",
    "urlWebp": "/images/gallery/thumbs/hackseries-25-23.webp"
  },
  {
    "id": "mq-5",
    "url": "/images/gallery/thumbs/hackseries-25-36.jpg",
    "alt": "HackSeries 25th Showcase & Felicitation #6",
    "urlWebp": "/images/gallery/thumbs/hackseries-25-36.webp"
  },
  {
    "id": "mq-6",
    "url": "/images/gallery/thumbs/hackathon-main-1.jpg",
    "alt": "National Hackathon Pitch Stage #1",
    "urlWebp": "/images/gallery/thumbs/hackathon-main-1.webp"
  },
  {
    "id": "mq-7",
    "url": "/images/gallery/thumbs/hackathon-main-6.jpg",
    "alt": "National Hackathon Pitch Stage #6",
    "urlWebp": "/images/gallery/thumbs/hackathon-main-6.webp"
  },
  {
    "id": "mq-8",
    "url": "/images/gallery/thumbs/hackathon-main-14.jpg",
    "alt": "Jury Evaluation & Architecture Review #1",
    "urlWebp": "/images/gallery/thumbs/hackathon-main-14.webp"
  },
  {
    "id": "mq-9",
    "url": "/images/gallery/thumbs/hackathon-bts-1.jpg",
    "alt": "ACES Organizing Crew & Operations #1",
    "urlWebp": "/images/gallery/thumbs/hackathon-bts-1.webp"
  },
  {
    "id": "mq-10",
    "url": "/images/gallery/thumbs/hackathon-bts-11.jpg",
    "alt": "ACES Organizing Crew & Operations #11",
    "urlWebp": "/images/gallery/thumbs/hackathon-bts-11.webp"
  },
  {
    "id": "mq-11",
    "url": "/images/gallery/thumbs/german-event-1.jpg",
    "alt": "Indo-German Tech & Academic Exchange #1",
    "urlWebp": "/images/gallery/thumbs/german-event-1.webp"
  },
  {
    "id": "mq-12",
    "url": "/images/gallery/thumbs/hackseries-01-1.jpg",
    "alt": "HackSeries 0.1 Inception & Kickoff #91",
    "urlWebp": "/images/gallery/thumbs/hackseries-01-1.webp"
  }
];
